<a href="https://colab.research.google.com/github/AnIsAsPe/Algebra_lineal-para-ML/blob/main/Notebooks/00%20Introducci%C3%B3n_a_numpy_para_Algebra_Lineal.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

#Funciones

## np.array()

### Crear un vector (1-D array)

In [ ]:
lista = [1,2,3]
vector = np.array(lista)
vector

array([1, 2, 3])

### Crear un vector (2-D array)

In [ ]:
lista2 = [[1,2,3], [4,5,6],[7, 8, 9]]
vector2 = np.array(lista2)
vector2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## np.arange()

parecido a range()

In [ ]:
for i in range(0,10,2):
  print(i)

e = range(0,10,2)
e

0
2
4
6
8


range(0, 10, 2)

In [ ]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

## np.linspace()



In [ ]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

## np.zeros()



In [ ]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

## np.ones()



In [ ]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## np.eye()  

Matriz identidad



In [ ]:
np.eye(5, k=0)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## np.random


In [ ]:
np.random.rand(3,3)

array([[0.55639316, 0.67067397, 0.25515331],
       [0.58259528, 0.63191837, 0.8262338 ],
       [0.73076234, 0.40290863, 0.72471795]])

In [ ]:
np.random.randint(1,20,3)

array([17,  4,  4])

#Atributos

## shape



In [ ]:
vector2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
vector2.shape

(3, 3)

In [ ]:
arr = np.arange(24)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [ ]:
arr.shape

(24,)

#Métodos

## reshape()



In [ ]:
arr.reshape(6,-1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

## min()  max()  sum() mean() 



In [ ]:
print(arr)
arr.max()

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


23

In [ ]:
print(vector2)
vector2.max()

[[1 2 3]
 [4 5 6]
 [7 8 9]]


9

In [ ]:
vector2.sum()

45

In [ ]:
arr.mean()

11.5

# Propiedad transmitiva de numpy arrays

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [ ]:
arr1 = arr[0:3]
arr1

array([0, 1, 2])

In [ ]:
arr1[:] = 20

arr1 

array([20, 20, 20])

In [ ]:
arr

array([20, 20, 20,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

arr1 no es una copia, es una vista de arr, para evitar esto, se debe hacer una copia

In [ ]:
arr2=arr.copy()
arr2

array([20, 20, 20,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [ ]:
arr1 = arr2[-3:]
arr1[:] = 200
arr1 

array([200, 200, 200])

In [ ]:
arr2

array([ 20,  20,  20,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20, 200, 200, 200])

In [ ]:
arr

array([20, 20, 20,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

## Modulo de [algebra lineal en numpy](https://numpy.org/doc/stable/reference/routines.linalg.html)

